### ISSUE TITLE
Tag for 0.5

### ISSUE THREAD

**Issue by PallHaraldsson** [aviks/JavaCall.jl#40]
https://github.com/JuliaDB/JDBC.jl/pull/20 says it's needed.

I'm not sure if 0.5 is already done with:
https://github.com/aviks/JavaCall.jl/commit/66af85a69c43af18a784313a5f41ebb4925b393c

as I see tests failing. Is that a false alarm since there is no tag? I'm just new to this, and can't see the test [that are failing]..

**Comment by aviks** [comment]
JavaCall v0.4.0 tagged with julia 0.5 support
