### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by ssagaert** [aviks/JavaCall.jl#6]
I can run a query 4 times correctly but the 5th time it crashes when doing ResultSet.getString("field")

in Java 7 this gives a NullPointerException
in Java 8 (after disabling the assertion for JNI version 1.6 to be able to run it) it crashes julia itself with a segmentation fault:

julia testRandom.jl 
Found libjvm @ /usr/lib/jvm/java-8-oracle/jre/lib/amd64/server
loading data

signal (11): Segmentation fault
jl_f_get_field at /usr/bin/../lib/x86_64-linux-gnu/julia/libjulia.so (unknown line)
geterror at /home/steven/.julia/v0.3/JavaCall/src/JavaCall.jl:209
_jcall at /home/steven/.julia/v0.3/JavaCall/src/JavaCall.jl:276
jl_apply_generic at /usr/bin/../lib/x86_64-linux-gnu/julia/libjulia.so (unknown line)
jl_f_apply at /usr/bin/../lib/x86_64-linux-gnu/julia/libjulia.so (unknown line)
jcall at /home/steven/.julia/v0.3/JavaCall/src/JavaCall.jl:236
jl_apply_generic at /usr/bin/../lib/x86_64-linux-gnu/julia/libjulia.so (unknown line)
loadData at /media/sf_Documents/julia_workspace/VMRecommender/src/VMRecommender.jl:194

**Comment by aviks** [comment]
I believe this should now be fixed on master, via https://github.com/aviks/JavaCall.jl/commit/6993eb6c834a3358453dd96e6cefe0e94617eaf4
